apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: abcd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-container
        image: abhinav9111/to-do-app:v1
        ports:
        - containerPort: 8000
