apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: abcd
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8000         
      targetPort: 80
      nodePort: 30000   
